# Build for GR 3.9.2 to support existing customers.
# Also build for latest GR 3.9.x that conda-forge supports
# for a given version of python.
python:
    - 3.8
    - 3.9
gnuradio:
    - 3.9
    - 3.9.2
numpy:
    - 1.20
