/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-wavelearner
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_WAVELEARNER_API_H
#define INCLUDED_WAVELEARNER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_wavelearner_EXPORTS
#define WAVELEARNER_API __GR_ATTR_EXPORT
#else
#define WAVELEARNER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_WAVELEARNER_API_H */
